sudo: required
language: c++
osx_image: xcode10.1
os:
- linux
- osx

# use travis encrypt TWINE_PASSWORD=password from within this directory to generate the secure key below.
env:
  global:
    - TWINE_USERNAME=cmeyer
    - secure: "W+Uz+fKMBNkrFT58V9QgAqh3ezF4HCc0fpKXFDylqfQ7BqbeY0IyiK4U4aC484cNLiZCuRekercOKnoVVKWfJwWnwQOxiVTRfz8u/LeMEWT4S5uqe2udcIAgwznS2kLwtXCrft7+0N8EuxAR/SS14mQVUqmSy3ZDWs2FJfi0EZlP5QlC4UYkKDNuuWum1J9CuWZTlaYmRNNG/oIvb3jPF+ivMvquPIuOEUul9bbhNAnjupKA6K1fvE12ro5+GFFJiQiy/iT9jWvsFK8VnR185S26Wv8b+t9sqvlmmnA46pajX0y5DzLH2puGszLBfOJz7cdwAsoEIqQvQQeKhqhs7nJxEpWzKRWlGK47LMV9wM4jCsGZ4SlgeYDlcfz6m7wPiXIwlbcAl/Z0a6/wymJohXgb5SgBS2+ulmo29SnADQny46mZJmv+EC9n3Cd07JNDSLDaJvh5GNwiapzcD6z5HTqWVq4o0YJGITKCFvXHjtklm4NjCWa7nx700lTzcZLkaWJl7SLCyW1yqb/640caJQbEtU7oNQj/X7LOH7feaidTTGNDgUkQ8sJaxHGjnad1f2AtXsqMVGlgxedeVrD5VZWq1SmxVXPK4iZa5MJFTrpvna9paBGb7CVfMZIGFYFhQguSWOoqcCPy5sVc71x8noe/NRmHedjXsTjX5hrOI1s="

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install numpy==1.15; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed -i '' 's/QTDIR = $(HOME)\/Developer\/Qt\/5.12.0\/clang_64/QTDIR = \/usr\/local\/opt\/qt5/g' launcher/xcconfig/targetReleaseNionUILauncher.xcconfig; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed -i '' 's/PYTHONHOME = $(HOME)\/Developer\/miniconda43/PYTHONHOME = \/usr\/local\/opt\/python3\/Frameworks\/Python.framework\/Versions\/3.7/g' launcher/xcconfig/targetReleaseNionUILauncher.xcconfig; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - python3-dev

script:
  bash travis-build.sh

after_success:
  # if tagged, create the source distribution and upload to PyPI
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      cd ${TRAVIS_BUILD_DIR}
      ~/miniconda/bin/python -m pip install twine
      ~/miniconda/bin/twine upload dist/*.whl
    fi

# use travis travis setup releases from within this directory to generate the secure key below.
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "TjtvdigepHd5ZalpMWJpnqVERjX3pDV04idrxg4XnwT2rnQ1XFkAtxzvxrkdMNWQyU0v3zS+gK/8ifVf9fb7EGsl30tZLJZFlcN3XoPaCFiwWBYlYc+NbJP1GAO4cj8rNQaiXtLA4e1ymMbqf3S/lfCiI6RJhufpKq+j1LtlHChg4TvnHvBoYyKuymYy29HFJAMWs1dHxUQPD1f9bepgTh7oPmcy3PsVZ3H/+OmmiNG5Niia3hYCErsVZiVRloHIVmQTFC+5iuzUhaDX9NkIz1ICxtNxINyuOqAh9awzdRS6g6IyFXuXl7HFXj7sW0af1pH6uGNh/bfVYAzPwRYtOFfLoKv8TWVw6sFEQOTr6U+F5y2WAmDkRV9lH6+yjD4SIZ6uesd5e9ii/7FOtGZpu000iJB744sZiy240i08H7tNSBiGLSoBZmT3UWunktLCQ2Ku00sCaw28ru1HvD5vZPHW4elPUGQ4KRVho/d2nIpDyGhAhjFChCt05B7haEPmqf9+4FwmdA3suGrueqbRrMosB3fAFtpNP0Cc9KNxx4QTt+zz863TVozvrAylvTa+O69SdQvbvPFSwP9Xc4qvufigaqY4/CuEpIQdnIZoP10LBTQefbhIghYLmPLFYQy0o9aA4EMs/8YgGweHvaesBwgQud0ps0NXzOoO3hXmJHE="
  file: dist/*.whl
  file_glob: true
  prerelease: true
  on:
    repo: nion-software/nionswift-tool
    tags: true
