package:
  name: 'nionswift-tool'
  version: '0.3.12'

source:
  - path: nion
    folder: nion
  - path: setup.py
  - path: NionSwiftLauncher-Mac.zip  # [osx]
  - path: NionSwiftLauncher-Windows  # [win64]
    folder: NionSwiftLauncher-Windows
  - path: NionSwiftLauncher-Linux.zip  # [linux64]

build:
  number: 0
  include_recipe: False
  entry_points:
    - nionswift-tool = nion.nionswift_tool.command:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python >=3.5

about:
  home: https://github.com/nion-software/nionswift-tool
  license: GPL-3.0
  summary: Nion Swift native launcher.
  description: "A native launcher for Nion Swift."

extra:
  recipe-maintainers:
    cmeyer
